#!/usr/bin/python
# -*- coding: utf-8 -*-
# old_style:google style:google
r"""
    全てのLODの基礎モジュール。
    
    Dates:
        date:2017/03/01 8:48[Eske](eske3g@gmail.com)
        update:2025/06/01 22:06 Eske Yoshinob[eske3g@gmail.com]
        
    License:
        Copyright 2017 Eske Yoshinob[eske3g@gmail.com] - All Rights Reserved
        Unauthorized copying of this file, via any medium is strictly prohibited
        Proprietary and confidential
"""
from gris3 import constructors, func, node
cmds = func.cmds

LOD_LIST = ['high', 'low']

class Constructor(constructors.currentConstructor()):
    def init(self):
        r"""
            主にExtraConstructorのインストールなどを行う。
        """
        # self.installExtraConstructor('constructorName')
        pass

    def createController(self):
        r"""
            コントローラ作成の記述を行うメソッド。
        """
        # self.toController('ジョイント名', 'セット名')
        pass
